
// Objective-C API for talking to the following Go packages
//
//	git.iotserv.com/iotserv/explorer/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Explorer_FRAMEWORK_H__
#define __Explorer_FRAMEWORK_H__

#include "Explorer.objc.h"
#include "Universe.objc.h"

#endif
