// Objective-C API for talking to git.iotserv.com/iotserv/explorer/mobile Go package.
//   gobind -lang=objc git.iotserv.com/iotserv/explorer/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Explorer_H__
#define __Explorer_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void ExplorerRun(NSString* _Nullable dbPath);

#endif
